### ISSUE TITLE
large workbook(~10mb) publish with chunk upload not working.. 

### ISSUE THREAD

**Issue by niravmpatel** [russch/PublishTDE#1]
here is the log from tableau server.

2015-11-13 10:29:58.851 -0500_level=ERROR_server=10.40.16.25:clt3dev1web00_service=WEB-INF:0_pid=8168_tid=0x75bc1a31_site=Bose_user=nirav.patel@siemens.com_session=_request=VkYB9gooEBkAABns7uMAAAFB_context=workbooks.publish_message=
Failed to publish workbook '26354:61789E86232B439F9CD6EC4C43954882-0:0' due to 'com.tableausoftware.domain.exception.NativeException: An unexpected error occurred opening the packaged workbook.
' backtrace is 'com/tableausoftware/model/workgroup/service/publishing/PublishingHelperService.java:652:in
`convertTableauException'com/tableausoftware/model/workgroup/service/publishing/WorkbookPublishingService.java:395:in
`processRestApiKeychain'com/tableausoftware/model/workgroup/service/publishing/WorkbookPublishingService.java:300:in
`publishWorkbookFromRestApi'com/tableausoftware/model/workgroup/service/publishing/WorkbookPublishingService.java:216:in
`publishWorkbookFromExternalClient'com/tableausoftware/domain/content/WorkbookService.java:1709:in
`publishWorkbook'com/tableausoftware/api/rest/impl/PublishingService.java:182:in
`publishWorkbook'app/controllers/api/workbooks_controller.rb:426:in
`publish'org/jruby/RubyKernel.java:2076:in
`send'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_controller/metal/implicit_render.rb:5:in
`send_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/abstract_controller/base.rb:150:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_controller/metal/rendering.rb:11:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/abstract_controller/callbacks.rb:18:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/callbacks.rb:574:in
`_run__1793163640__process_action__1718727594__callbacks'org/jruby/RubyKernel.java:2076:in
`send'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/callbacks.rb:425:in
`_run_process_action_callbacks'org/jruby/RubyKernel.java:2080:in
`send'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/callbacks.rb:94:in
`run_callbacks'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/abstract_controller/callbacks.rb:17:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/common/ruby/rails-hooks/hook_action_controller.rb:84:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/notifications.rb:52:in
`instrument'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/notifications/instrumenter.rb:21:in
`instrument'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/notifications.rb:52:in
`instrument'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/common/ruby/rails-hooks/hook_action_controller.rb:83:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_controller/metal/rescue.rb:17:in
`process_action'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/abstract_controller/base.rb:119:in
`process'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/abstract_controller/rendering.rb:41:in
`process'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_controller/metal.rb:138:in
`dispatch'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_controller/metal/rack_delegation.rb:14:in
`dispatch'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_controller/metal.rb:178:in
`action'org/jruby/RubyProc.java:270:in
`call'org/jruby/RubyProc.java:220:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/routing/route_set.rb:62:in
`dispatch'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/routing/route_set.rb:27:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb:148:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:111:in
`recognize'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:2404:in
`optimized_each'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:110:in
`recognize'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb:139:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/routing/route_set.rb:493:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/best_standards_support.rb:17:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/head.rb:14:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-1.2.2/lib/rack/methodoverride.rb:24:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/params_parser.rb:21:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/config/initializers/no_parse.rb:29:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/flash.rb:182:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/session/abstract_store.rb:149:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/cookies.rb:302:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/config/initializers/session_store.rb:48:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activerecord-3.0.7/lib/active_record/query_cache.rb:32:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/query_cache.rb:28:in
`cache'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activerecord-3.0.7/lib/active_record/query_cache.rb:12:in
`cache'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activerecord-3.0.7/lib/active_record/query_cache.rb:31:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/callbacks.rb:46:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/activesupport-3.0.7/lib/active_support/callbacks.rb:431:in
`_run_call_callbacks'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/callbacks.rb:44:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-1.2.2/lib/rack/sendfile.rb:107:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/remote_ip.rb:48:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/show_exceptions.rb:47:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/railties-3.0.7/lib/rails/rack/logger.rb:13:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/rack-1.2.2/lib/rack/runtime.rb:17:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/actionpack-3.0.7/lib/action_dispatch/middleware/static.rb:30:in
`call'C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/gems/gems/railties-3.0.7/lib/rails/application.rb:168:in
`call'file:/C:/Program Files/Tableau/Tableau Server/9.1/wgserver/z5/WEB-INF/lib/gems-gems-jruby-rack-1.0.8-lib-jruby-rack-1.0.8.jar!/rack/handler/servlet.rb:19:in
`call''

**Comment by niravmpatel** [comment]
here is the java code we use for chunk upload:Please find attached rest api utils.java

```
private WorkbookType invokePublishWorkbookChunked(TableauCredentialsType credential, String siteId,
        String projectId, String workbookName, File workbookFile, boolean overWrite) {

    m_logger.info("workbookname is "+workbookName);
    m_logger.info("workbookFile is "+workbookFile.getPath());
    String tmpFile = "";
    try{
    // Initiates a new file upload to get an upload session id
    FileUploadType fileUpload = invokeInitiateFileUpload(credential, siteId);

    // Builds the URL with the upload session id and workbook type
    UriBuilder builder = Operation.PUBLISH_WORKBOOK.getUriBuilder()
            .queryParam("uploadSessionId", fileUpload.getUploadSessionId())
            .queryParam("workbookType", Files.getFileExtension(workbookFile.getName()));
    String url = builder.build(siteId, fileUpload.getUploadSessionId()).toString();

    // Creates a buffer to read 100KB at a time
    byte[] buffer = new byte[100000];
    m_logger.info("\n\n before invokding append file upload");
    // Reads the specified workbook and appends each chunk to the file upload
    tmpFile = System.getProperty("java.io.tmpdir")+File.separator+"appendFileUpload.temp";
    try (FileInputStream inputStream = new FileInputStream(workbookFile.getAbsolutePath())) {
        while (inputStream.read(buffer) != -1) {
            m_logger.info("\n\n invokding append file upload");
            invokeAppendFileUpload(credential, siteId, fileUpload.getUploadSessionId(), buffer, tmpFile);
        }
    } catch (IOException e) {
        throw new IllegalStateException("Failed to read the workbook file.");
    }

    // Creates the payload to publish the workbook
    TsRequest payload = createPayloadToPublishWorkbook(workbookName, projectId);

    // Makes a multipart POST request with specified credential's
    // authenticity token and payload
    TsResponse response = postMultipart(url, credential.getToken(), payload, null);
    // Verifies that the response has a workbook element
    if (response.getWorkbook() != null) {
        m_logger.info("Publish workbook is successful!");

        return response.getWorkbook();
    }
    }finally{
        //delete temp file.
        try{
            m_logger.info("deleting temp file appendFileUpload.temp at:"+tmpFile);
            File tempfile = new File(tmpFile);
            if(tempfile != null){
                tempfile.delete();
            }

            m_logger.info("deleted temp file appendFileUpload.temp at:"+tmpFile);
        }catch(Exception ex){
            m_logger.error("error while deleting tmpFile:"+tmpFile,ex);
        }
    }
    // No workbook was published
    return null;
}
```

**Comment by russch** [comment]
Nirav, your code and approach has nothing to do with the sample code I posted except that it is publishing something via the REST API. I'm therefore closing this. 

Suggestions: 
- If you are having problems with your code, engage on the Tableau Developer Forums (https://community.tableau.com/community/developers)
- Don't hit Tech Support as they don't support any custom code. Even though your code started it's life as one of Tableau's samples, it is "custom code" once you use it outside of the sample itself.
- Work through the readme of the Java Sample code and test the original sample code AS IS without ANY CHANGES. See if it works.
